### PR TITLE
[LD-1345][LD-1380] Install terraform as part of jenkins lineman slave

### PR DESCRIPTION
**Pull request by faizhasim**
@learndot/developers @learndot/servicerocket

### CODE REVIEW

**Comment by herrowna** [comment]
That looks fine.

**Comment by faizhasim** [comment]
Thanks @herrowna :100:

**Comment by yclian** [comment]
@faizhasim  Just to understand the process, do you use Jenkins to run Terraform, or? Can you give some context?

**Comment by faizhasim** [comment]
Yes. https://ld-ci.performancerocket.com/job/infrastructure-single-page-application-web/

Our jenkins slave is now capable of running terraform.

But, during early development, we trigger atlas from local machine. 

                  
Mohd Faiz Hasim
Architect
www.servicerocket.com                     

On 23 December 2015 at 10:08:16 AM, Yuen-Chi Lian (notifications@github.com) wrote:

@faizhasim Just to understand the process, do you use Jenkins to run Terraform, or? Can you give some context?

**Pull request merged**
